### ISSUE TITLE
Variant not displayed in test explorer VS Mac 2022

### ISSUE THREAD

**Issue by jmichas** [TotalTest/SpecFlow.Contrib.Variants#7]
Hi,
So, I have been trying to figure out what is going on and where the problem lies.
I updated my projects to net7 and lates VS Mac and updated all nugets to the latest net7 compatible.
After that I found that my UI project tests no longer displayed the variant in the explorer.

Please [see my old stack question](https://stackoverflow.com/questions/72884377/how-to-run-the-same-specflow-test-for-ios-and-android-using-appium) for some screen shots.

It appears the "old" way I note in my stack post (adding a scenarios table) works still, but the variant plugin does not.

Is this an issue with your code or something the VS people removed?

Thanks for any info.

**Comment by TotalTest** [comment]
Hi, I've created a net7 project on windows visual studio 2022 (latest version) and the plugin works fine. I've attached an image to show the .csproj file with the relevant framework and packages. It might be worth trying the same to see if in fact it is an issue with VS on Mac. I've attached a zip of the net7 project so you can easily try it on your mac. 

Also one thing to check is the *feature.cs file (the code generated file for the feature file). On around line 13 there should a comment: "// Generation customised by SpecFlow.Contrib.Variants"  - this means the plugin done what it needed to ok.

![Screenshot 2023-12-04 004313](https://github.com/TotalTest/SpecFlow.Contrib.Variants/assets/10982432/bf21536f-3797-462f-9c93-64546e87a3c7)
[SpecflowVariantsPlayground.zip](https://github.com/TotalTest/SpecFlow.Contrib.Variants/files/13540809/SpecflowVariantsPlayground.zip)
