### ISSUE TITLE
Scenario displayed only once in LivingDoc report due to identical scenario title for multiple browsers

### ISSUE THREAD

**Issue by ghost** [TotalTest/SpecFlow.Contrib.Variants#8]
Having multiple browsers will output the given browser number of results in the report .json file.
Due to the scenario title not being different between browsers, the report will only contain the first result for the first browser mentioned in tags.

Is there any way to incorporate the browser from the tag, for example, @ Browser:Chrome -> Chrome_{Scenarion_Title), in the scenario title?

Thanks!

**Comment by TotalTest** [comment]
The scenario title does currently append the variant (browser in your case). e.g.
![image](https://github.com/user-attachments/assets/c681c04b-2a72-4610-8978-11548e9468a4)
 
Could you provide more details?
 - an example where I can reproduce
 - which unit test provider are you using (nunit, mstest, xunit)? 
 - what version of .net (framework or core)?

**Comment by criistra** [comment]
Hi!

![image](https://github.com/user-attachments/assets/f4a27d9c-19f2-4007-b77c-926650af3175)
![image](https://github.com/user-attachments/assets/e7b46c0b-de5e-45a2-ac4a-53e2274e646f)

TestExecution.json:
![image](https://github.com/user-attachments/assets/7e43b02d-a7fe-4b1b-891f-31efaf6ce4d3)

Generated .cs file:
![image](https://github.com/user-attachments/assets/01e454be-2cf8-4890-af06-db79b57059d0)

Packages:
![image](https://github.com/user-attachments/assets/f814636a-fbd9-4be1-9f9b-a8dddb2ad5c5)

- which unit test provider are you using (nunit, mstest, xunit)?
- - NUnit - latest
- what version of .net (framework or core)?
- - .NET 8


This is how it looks in living doc.
![image](https://github.com/user-attachments/assets/a84f9e64-f265-4fcc-93aa-cac34899eaff)

It says the test ran 3 times, but I cannot see the results for all of them.
I guess if the scenario name can be adapted to include the browser name in ScenarioInfo, it will also show show all runs in LivingDoc.
![image](https://github.com/user-attachments/assets/984755d9-0031-4a78-b355-150ce1b0b73e)

**Comment by TotalTest** [comment]
Hi @criistra, I have publshed a pre-release version to cater for the above. Please could you give it a go and let me know if it solves your problem?

`dotnet add package SpecFlow.Contrib.Variants --version 3.9.90-pre.2`

**Comment by criistra** [comment]
Hi @TotalTest, now the browser is added in the ScenarioInfo and it's also displayed in the TestExecution.json file.

The new problem is that LivingDoc does doesn't know how to match the scenario title from the .feature file with the scenario names from the TestExecution.json. 

For example, if the scenario title from the .feature file is "Some scenario title" and the scenario title from the TestExecution.json is "Some scenario title: Chrome", livingdoc won't match them to have results, so the .html is generated without test execution results.
![image](https://github.com/user-attachments/assets/34ea09b2-5ecf-4fe5-a6fb-c54cc4eece46)

Removing the additional ": {browser.name}" from the TestExecution.json file for each scenario will lead back to the old issue in which the results are not displayed separately for each browser.

I can live with it, I will skip using LivingDoc and rely on the .TRX file which displays all results properly in Azure, for each browser.
![image](https://github.com/user-attachments/assets/2b7f65dd-5ce1-4848-8f7c-4ac54253ad51)

I do not think there is something else that can be done from your side. I believe it's ok to revert those changes if it doesn't help on your side with something else.

**Comment by ghost** [comment]
Hi @TotalTest, now the browser is added in the ScenarioInfo and it's also displayed in the TestExecution.json file.

The new problem is that LivingDoc does doesn't know how to match the scenario title from the .feature file with the scenario names from the TestExecution.json. 

For example, if the scenario title from the .feature file is "Some scenario title" and the scenario title from the TestExecution.json is "Some scenario title: Chrome", livingdoc won't match them to have results, so the .html is generated without test execution results.
![image](https://github.com/user-attachments/assets/0b6793f3-d41e-4b6e-9e10-9f6613248743)

Removing the additional ": {browser.name}" from the TestExecution.json file for each scenario will lead back to the old issue in which the results are not displayed separately for each browser.

I can live with it, I will skip using LivingDoc and rely on the .TRX file which displays all results properly in Azure, for each browser.
![image](https://github.com/user-attachments/assets/2b7f65dd-5ce1-4848-8f7c-4ac54253ad51)

I do not think there is something else that can be done from your side. I believe it's ok to revert those changes if it doesn't help on your side with something else.

Thank you!

**Comment by TotalTest** [comment]
Yeah it seems living doc doesn't take scenario names from the generated code behind files so it won't know about the variants. 

I think it's still correct to have these changes in as the scenario info does actually represent the test.
